name: bump
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    name: increase version numbers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: configure git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: update changelog
        run: | 
          npx generate-changelog -p
          git add CHANGELOG.md
          git commit -m 'updated CHANGELOG.md'

      - name: bump version
        run: npm version ${{ github.event.inputs.version }} -m "bump to %s"
        
      - name: git push
        run: git push origin 