name: publish
on:
  workflow_dispatch: # manually run
    inputs:
      releaseTag:
        description: 'Tag the release (next, latest)'
        required: false
        default: 'latest'

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Authenticate with Registry
        run: |
          echo "always-auth=true" > .npmrc
          echo "@subsquid:registry=https://registry.npmjs.org/" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Install dependencies
        run: |
          npm i
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Build
        run: npm run build

      - name: Verify package
        run: |
          npm pack --dry-run
          npm run test || true

      - name: Publish to npm
        run: |
          npm publish --tag $RELEASE_TAG --access public
        env:
          RELEASE_TAG: ${{ github.event.inputs.releaseTag }}
        continue-on-error: false
